Client: 
    ID: '1241792946882351155' # Bot ID
    Guild: '1234065450011328513' # Guild ID
    Version: '1.0.0' 

Ready:
    Activity: 'DevXor Team' 
    Status: 'DND'  # Online, Idle, Invisible, DND
    Type: 'Competing' # Playing, Watching, Listening, Competing

#ID Owners Bot
Owners: 
    - '620201132039602188'
    - '569893348014555149'
